---
title: "RR course"
author: "Yuan Du"
date: "May 29, 2019"
output: html_document
---

*Italic*
**Bold**

[A hyperlinke](https://google.com)

- Abulleted list
- Another list item

1. A numbered list
2. A second numbered item
    1. sub-item 1
        1. sub-sub item

* unordered list
    + sub-item
    
```{r global_options, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "figs/")
```
 
 
```{r}
library("gapminder")
library("ggplot2")
library("tidyverse")
library("dplyr")
data(gapminder)
head(gapminder)
```
```{r gdp_lifeexp_plot}
ggplot(data = gapminder, mapping = aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```

```{r gdp_lifeexp_over_time, echo = FALSE}
ggplot(data = gapminder, mapping = aes(x = year, y = lifeExp)) +
  geom_point()
```
 
```{r gdp_lifeexp_over_time2, eval= FALSE}
ggplot(data = gapminder, mapping = aes(x = year, y = lifeExp)) +
  geom_point()
```
```{r gdp_lifeexp_over_time3, results= "hide"}
ggplot(data = gapminder, mapping = aes(x = year, y = lifeExp)) +
  geom_point()
```

```{r gdp_lifeexp_over_time4, fig.width=3, fig.height=3}
ggplot(data = gapminder, mapping = aes(x = year, y = lifeExp)) +
  geom_point()
```
The lagest population of any country in this dataset is `r max(gapminder$pop)`
```{r iceland, echo = FALSE}
iceland <- filter(gapminder, country == "Iceland")
max_iceland_lifeexp <- max(iceland$lifeExp)
```
The maximium life expectancy in Iceland is `r max_iceland_lifeexp`.

```
git config --global user.name "Yuan Du"
git config --global user.email "Yuan.du@adventhealth.com"
git config --global core.editor 'nano'
git init
```

Here is some more text that I am adding.